# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
