# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='langugae',
            new_name='language',
        ),
    ]
